
services:
  biamino-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - biamino-data:/data
    environment:
      - PORT=3001
      - DATABASE_PATH=/data/database.sqlite

volumes:
  biamino-data:
