
version: '3.8'

services:
  biamino-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - biamino-data:/data
    environment:
      - PORT=3001

volumes:
  biamino-data:
